### PR TITLE
fix(build): Fix package.json

### PR DESCRIPTION
**Pull request by DmACKGL**
Added webpack (required for build)
Added @octokit/core (required by lerna)
Pre-Commit to NPX

### CODE REVIEW

**Comment by jfrader** [comment]
Hey! Thanks for contributing!!!

Is this to fix build warnings or is there another purpose too?

**Comment by DmACKGL** [comment]
> Hey! Thanks for contributing!!!
> 
> Is this to fix build warnings or is there another purpose too?

Hey @jfrader!
This commit fixes all yarn install warnings and there's no need to install webpack globally now.

**Comment by jfrader** [comment]
What is octokit tho?

**Comment by TasoOneAsia** [comment]
Webpack shouldn't be required for builds in this case especially in root repo, lerna run will simply use the context of each package in the run command. As our webpack differs heavily between NUI and game scripts I don't see the need to consolidate those in root directory. Also I am not sure where the octokit dependency is for as it is building fine at the moment? Can you please provide information about what exactly this pull requests fixes? Thanks

**Comment by DmACKGL** [comment]
Hey @TasoOneAsia!

If the developer doesn't have Webpack installed globally, it will get 'Webpack not found' when executing yarn build in the root directory, installing Webpack as an in-project DEV requirement would automatically install it on the node_modules (Not globally, this is important due to the fact this project uses Webpack 4 and is not compatible with Webpack 5 at the moment.)
image
Note: if you run yarn install on the phone directory first, it fixes the issue too; this is more for fast build (clone & deploy) setups.

Regarding the Octokit/Core package addition is because it is marked as an unmeet peed dependency (from Octokit/plugin/request/log), this change removes this warning completely 

Happy to help!

**Comment by TasoOneAsia** [comment]
In regards to the issue you were having with first time build, was this after running `lerna boostrap` in the root repository or did you not run this command when cloning. Bootstrap should immediately install and symlink common deps.

If the octocore package is indeed a peer dep, that addition is fine. Though I swear I didn't see any peer dep issues when I first setup lerna.

**Comment by DmACKGL** [comment]
@TasoOneAsia Looks like I made an error, including Webpack; I'm reviewing this pull right now; sorry for wasting your time.
Octocore warning: 
image

Changing this pull to Draft.

**Comment by TasoOneAsia** [comment]
No problem, thanks for contributing :) 

Once this PR is ready, i'll be happy to review it again 👍

**Comment by DmACKGL** [comment]
Ready for review, I added https://github.com/mysticatea/npm-run-all to run yarn install on phone and resources folder.

**Review by TasoOneAsia — APPROVED** [review]
lgtm

**Pull request merged**
