### PR TITLE
Refactor/events enums

### PR DESCRIPTION
**Pull request by TasoOneAsia**
Switches net events in cl/sv to using enums rather than the events object.

### CODE REVIEW

**Review by jfrader — COMMENTED** [review]
Could you replace Nui.send in frontend as well?

**Review by erik-sn — APPROVED** [review]
This is great, I had something like this done for Twitter individually but doing them all in one go is best.

Have you thought about prepending every event with `npwd:` (like `npwd:myCoolEvent`) just so it is namespaced and there will never be a possibility of collision with another package?

**Review by jfrader — APPROVED** [review]

**Comment by TasoOneAsia** [comment]
> Have you thought about prepending every event with `npwd:` (like `npwd:myCoolEvent`) just so it is namespaced and there will never be a possibility of collision with another package?

Yea we can do that, should be pretty easy now with the enums.

Also @erik-sn & @jfrader just pushed a commit with event enums attached to their respective Nui.send counterparts

**Comment by TasoOneAsia** [comment]
> Have you thought about prepending every event with `npwd:` (like `npwd:myCoolEvent`) just so it is namespaced and there will never be a possibility of collision with another package?

Just prefixed all events with the last commit

**Comment by TasoOneAsia** [comment]
Note this does break with `yarn start` as react-scripts is expecting all the modules to be within `./src` folder. This can be fixed with a couple of changes.

**Review by itschip — APPROVED** [review]
lgtm

**Comment by TasoOneAsia** [comment]
@jfrader @erik-sn  @itschip  If we are all good, I want to land this PR on master. So if you have any final comments, let me know

**Pull request merged**
