### PR TITLE
Enhance/settings

### PR DESCRIPTION
**Pull request by TasoOneAsia**

### CODE REVIEW

**Comment by RockySouthpaw** [comment]
Looks great to me. Tested all the functionality and the copying of your number works as well.

https://i.imgur.com/KgzE61d.png

This does make me realize Tasp-dark needs a slight additional variance between the 2 colors as it's a bit hard to see where the settings and nav bar ends.

**Comment by jfrader** [comment]
LGTM

**Comment by jfrader** [comment]
It would be awesome if we could merge this config with the one at root directory and make them .TS and type it.
What do you think @itschip @RockySouthpaw 

This way we would only have 1 config file for everything and as it is .ts we can strictly type it for better usage.

At least i would merge both into a json if not ts.

**Comment by RockySouthpaw** [comment]
For some reason, the blue phone case doesn't work in game as it shows up blank. I've tried this branch a total of 3 times now and the issue occurs each time. Not sure the cause.

**Review by itschip — COMMENTED** [review]
Works just fine, but I think we should set some default values?

**Comment by TasoOneAsia** [comment]
Will refactor onto latest to avoid all these conflicts in Phone.tsx

**Pull request closed without merging**
