### PR TITLE
feat(resources): remove all esx code, almost

### PR DESCRIPTION
**Pull request by itschip**
Removes almost all ESX code,.
[Feat: Remove ESX Code](https://app.gitkraken.com/glo/card/dae2624dcdcc45d9ab0077ad5fb58425)

### CODE REVIEW

**Review by TasoOneAsia — CHANGES_REQUESTED** [review]

**Comment by TasoOneAsia** [comment]
Needs to be reviewed by others

**Comment by RockySouthpaw** [comment]
So i tested this on my V1 Final server and here is the summary: 

- Number generating **only** works if they have a name already. 
     - On user first join they don't have a name which we try to fetch. Solution is to just remove this and make users 
- Theres some issues getting identifier when you open the phone. 
     -  https://cdn.discordapp.com/attachments/791854455468458042/818720637576282112/unknown.png
- Calling doesn't work currently at all as a result of the above issue.
- Theres an error as well when quiting while the server is up.

I made taso aware of the issues so its all in discord: Can follow it from here: https://discord.com/channels/791854454760013827/791854455468458042/818720640282394634

We will also need to include in some place that they need to be on at least `Artifact Version 3598`. I'll add to the Docs at some point.

**Comment by TasoOneAsia** [comment]
Fixed @RockySouthpaw

**Comment by RockySouthpaw** [comment]
@TasoOneAsia Will retest now.

**Comment by RockySouthpaw** [comment]
> * Number generating **only** works if they have a name already.
**Fixed** 
>   * On user first join they don't have a name which we try to fetch. Solution is to just remove this and make users
**Fixed** 
> * Theres some issues getting identifier when you open the phone.
**Fixed** 
> * Calling doesn't work currently at all as a result of the above issue.
**Fixed** 
> * Theres an error as well when quiting while the server is up.
**Fixed** 

PR is ready to be merged. 👍🏻

**Review by RockySouthpaw — APPROVED** [review]

**Comment by TasoOneAsia** [comment]
Will not be squashed/rebased as some commits have important comments

**Pull request merged**
