### PR TITLE
Notification alert stays on if it is an incoming call and phone is closed

### PR DESCRIPTION
**Pull request by jfrader**
Also can close alerts with X and the incoming call alert disappears if you open the phone and see the modal.
[Notification: Alert stays on if it is an incoming call and phone is closed](https://app.gitkraken.com/glo/card/5bed50e7148e45e18dfdac1ae92432e0)

### CODE REVIEW

**Comment by RockySouthpaw** [comment]
Will test sometime tonight and let you know :)

**Comment by RockySouthpaw** [comment]
Testing now. Will edit

**Comment by RockySouthpaw** [comment]
Icons within apps also dont adjust color when using the router.

1. Open Phone App
2. Click Dial
3. Click contacts
4. Click router

The router will transition correctly but the dial icon is still grey despite being focused, (Should be green.)

**Comment by jfrader** [comment]
@itschip can u check if your dialer change made the bugs @RockySouthpaw describes? U changed dialer app 😬

Tho I think the first one is already in master and introduced by another branch.

The second one I'm not sure

**Comment by jfrader** [comment]
For these tho I would just create new tickets

**Comment by itschip** [comment]
> @itschip can u check if your dialer change made the bugs @RockySouthpaw describes? U changed dialer app 😬
> 
> Tho I think the first one is already in master and introduced by another branch.
> The second one I'm not sure

@jfrader The things I changed were not mentioned as a bug 😂 but I'll look into them 🐛

**Review by itschip — APPROVED** [review]
LGTM 👍 We'll store what rocky said and fix those 'issues' in a new PR.

**Comment by RockySouthpaw** [comment]
Tested calling in game, LG2M.

Notifications for calling now works as such:
- If phone is closed and your screen resolution is 1080p, phone will pull up. You press F1 and it goes away.
- If your phone is already open, the notification isn't generated.

So all works well aside from the 3 known issues.

**Pull request merged**
