### PR TITLE
enhance(phone/settings): General enhancements

### PR DESCRIPTION
**Pull request by TasoOneAsia**
General enhancements to settings app

### CODE REVIEW

**Review by jfrader — APPROVED** [review]
Lgtm

**Comment by TasoOneAsia** [comment]
These our ***BREAKING*** changes to setting schema, if you do not reset settings, the phone will crash until further fallbacks are added for the SoundProvider.

**Review by erik-sn — APPROVED** [review]
We should probably implement a similar `Option` interface for the rest of the phone configuration at some point too.

**Comment by jfrader** [comment]
Yes i think everything should be in the same place in the root and get copied over or just imported.

**Comment by TasoOneAsia** [comment]
> Yes i think everything should be in the same place in the root and get copied over or just imported.
> @erik-sn @TasoOneAsia

To add, I actually think it would be best to have an JSON ignored from build that can be referenced by scripts. This way, when we get to the release stage, we can pre-webpack server/client files and still allow for end users to change the config. Also forcing a rebuild when changing the config is not gonna yield good results for the majority of the FiveM community  **"Developer"** base.

**Comment by RockySouthpaw** [comment]
Aside from the super small issue with notifications being highlighted in verse for twitter, it looks good to me. 👍🏻

**Pull request merged**
