### PR TITLE
Created locales' base for notifications + sound

### PR DESCRIPTION
**Pull request by XiosBombay**

### CODE REVIEW

**Comment by XiosBombay** [comment]
Do not merge plz

**Comment by jfrader** [comment]
The notification sounds PR has new keys as well, if you want to keep track of those changes itll be better for you to wait that is merged, or use that branch as starter.

**Comment by XiosBombay** [comment]
Where's the sound @jfrader ?

**Comment by XiosBombay** [comment]
I'll add it

**Comment by jfrader** [comment]
> I'll add it

https://github.com/project-error/new-phone-who-dis/pull/119

**Comment by XiosBombay** [comment]
Ok, that should have fixed it. People would just need to translate the base I made in English which should be pretty easy now that everything is organized.

**Review by jfrader — COMMENTED** [review]
Great Job!

**Review by jfrader — APPROVED** [review]

**Pull request merged**
