### PR TITLE
Fix the fucking esx errors :)

### PR DESCRIPTION
**Pull request by jfrader**
Show initializing phone message if not ready yet
Set phone ready before sending any init events

### CODE REVIEW

**Review by erik-sn — APPROVED** [review]
This is great. I think this should solve the problem well.

Do we understand why ESX takes a long time to load a player on some servers/environments? My only concern is that if the variation between users is high there could be some "bugs" where people don't get to use the phone. But that seems like an edge case.

**Review by itschip — APPROVED** [review]
Looks good!

**Comment by RockySouthpaw** [comment]
> This is great. I think this should solve the problem well.
> 
> Do we understand why ESX takes a long time to load a player on some servers/environments? My only concern is that if the variation between users is high there could be some "bugs" where people don't get to use the phone. But that seems like an edge case.

No we dont. If the variation exist to a point of causing breaking issues between two servers with less than 30 resources then the phone will not be stable with ESX being required for functionality.

Esx V1 already has non reproducible issues with spawning players turning into micheal and is almost a year beyond its final point. We shouldn’t even be dealing with ESX issues this late in the phone quite frankly as it should of been abstracted early on.

Regardless if this PR “solves” this issue (we haven’t tested it), we would be naive to rely on some work around to fix the underlying issues that reside within ESX.

**Comment by jfrader** [comment]
> > This is great. I think this should solve the problem well.
> > 
> > Do we understand why ESX takes a long time to load a player on some servers/environments? My only concern is that if the variation between users is high there could be some "bugs" where people don't get to use the phone. But that seems like an edge case.
> 
> No we dont. If the variation exist to a point of causing breaking issues between two servers with less than 30 resources then the phone will not be stable with ESX being required for functionality.
> 
> Esx V1 already has non reproducible issues with spawning players turning into micheal and is almost a year beyond its final point. We shouldn’t even be dealing with ESX issues this late in the phone quite frankly as it should of been abstracted early on.
> 
> Regardless if this PR “solves” this issue (we haven’t tested it), we would be naive to rely on some work around to fix the underlying issues that reside within ESX. 

Even tho what you say is true, these changes are needed now to continue the development knowing that we have the data we need now.

Also, these changes should be useful for when ESX is complete removed from this or at least abstracted our own data to work with, because we will still need to wait for the identifier and source to be available.

**Comment by jfrader** [comment]
> This is great. I think this should solve the problem well.
> 
> Do we understand why ESX takes a long time to load a player on some servers/environments? My only concern is that if the variation between users is high there could be some "bugs" where people don't get to use the phone. But that seems like an edge case.

I don't think difference between players in loading time should matter at all.

**Review by RockySouthpaw — APPROVED** [review]
Tested briefly and this pr removed the error with messages pertaining to loading. Should be merged to master and then test should be conducted on https://github.com/project-error/new-phone-who-dis/pull/147 as this was another instance of the issue.

**Pull request merged**
