### PR TITLE
feat(phone): Added a game time indicator to top bar

### PR DESCRIPTION
**Pull request by TasoOneAsia**
image

Adds the current game time to the top bar, the game time is sent every time the phone is opened. This can also be done in a set interval, but I have commented that for now.

### CODE REVIEW

**Comment by RockySouthpaw** [comment]
LG2M. Maybe a time format option instead of forcing the use of 24 hour time. 🤷🏻 only thoughts really.

**Comment by AvarianKnight** [comment]
Does this take into account if people decide to change the default game time MS? You can use [GetMillisecondsPerGameMinute](https://docs.fivem.net/natives/?_0x2F8B4D1C595B11DB) to check if they modified.

**Comment by TasoOneAsia** [comment]
> Does this take into account if people decide to change the default game time MS? You can use [GetMillisecondsPerGameMinute](https://docs.fivem.net/natives/?_0x2F8B4D1C595B11DB) to check if they modified.

There isn't live update intervals, I commented that part out for this exact reason. For the moment the game time is only sent when the phone is opened.

**Comment by TasoOneAsia** [comment]
> LG2M. Maybe a time format option instead of forcing the use of 24 hour time. 🤷🏻 only thoughts really.

I would need to add a whole bunch more time conversions functions for this 😢

**Comment by AvarianKnight** [comment]
> > Does this take into account if people decide to change the default game time MS? You can use [GetMillisecondsPerGameMinute](https://docs.fivem.net/natives/?_0x2F8B4D1C595B11DB) to check if they modified.
> 
> There isn't live update intervals, I commented that part out for this exact reason. For the moment the game time is only sent when the phone is opened.

Can you not just send the update interval every time the phone opens?

**Comment by TasoOneAsia** [comment]
I can, its just the interval spams our debug logs hard, so I don't wanna implement it just yet.

**Review by RockySouthpaw — APPROVED** [review]
Will need to make it up date in real time later on but tested and works fine.

**Pull request merged**
