### PR TITLE
replaced all imgur images to iodine images :)

### PR DESCRIPTION
**Pull request by Hamy-os**
dont mind the 347 changed files its cause i drag and dropped :alien:

### CODE REVIEW

**Comment by jfrader** [comment]
@Hamy-os what is the reasoning behind this change?

**Comment by Hamy-os** [comment]
> @Hamy-os what is the reasoning behind this change?

Iodine is the best in the buisness, Blazing fast CDN, geo location load balancing and much more! (also chip is part of it)

**Comment by jfrader** [comment]
@Hamy-os well that's good then. Do you mind updating the docs repository too?

**Review by jfrader — APPROVED** [review]

**Comment by Hamy-os** [comment]
> @Hamy-os well that's good then. Do you mind updating the docs repository too?

sure

**Comment by RockySouthpaw** [comment]
Will test later

**Pull request merged**
