### PR TITLE
Feat/alerts for apps (in memory of daft punk)

### PR DESCRIPTION
**Pull request by itschip**
[Alerts for Apps](https://app.gitkraken.com/glo/card/c566fdfb462944ffaf78f707525969c2)

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
RIP DAFT PUNK 😭

**Comment by RockySouthpaw** [comment]
Resolve conflicts pls.

**Review by jfrader — APPROVED** [review]
LGTM.

Can we delete everything about older alerts? There's BankNotifications and TwitterNotifications in PhoneContainer.tsx and prolly there's more stuff laying around unused

**Comment by itschip** [comment]
> Can we delete everything about older alerts? There's BankNotifications and TwitterNotifications in PhoneContainer.tsx and prolly there's more stuff laying around unused

@jfrader This should be done now.

**Comment by TasoOneAsia** [comment]
Tests failed after latest, can you double check?

**Review by jfrader — APPROVED** [review]
Nice!

**Pull request merged**
