### PR TITLE
Add wdyr and make AppRoute a pure component

### PR DESCRIPTION
**Pull request by jfrader**
Prevents infinite renders in some apps.
Adds why-did-you-render tool in development
Fixes re-renders in useKeyboard

### CODE REVIEW

**Review by itschip — APPROVED** [review]
LGTM!

**Comment by TasoOneAsia** [comment]
@jfrader Was not added to the package dependencies. Want me to ftfy?

**Review by TasoOneAsia — CHANGES_REQUESTED** [review]
`@welldone-software/why-did-you-render`, was not added to the package dependencies. Want me to ftfy?

**Comment by jfrader** [comment]
> `@welldone-software/why-did-you-render`, was not added to the package dependencies. Want me to ftfy?

If you need to yeah! Thanks!
I will update tomorrow if you can't today

**Pull request merged**
