### PR TITLE
Bugfix / New message autocomplete getting bricked

### PR DESCRIPTION
**Pull request by jfrader**

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
Interesting that this resolves the problems you were talking, will review in the morning.

**Comment by RockySouthpaw** [comment]
Will conduct testing tonight nodders

**Comment by jfrader** [comment]
> Interesting that this resolves the problems you were talking, will review in the morning.

It's not interesting lol it's same logic just forcing it :)

**Review by itschip — APPROVED** [review]

**Review by RockySouthpaw — APPROVED** [review]
Tested in game and pasted multiple times to try and break it. as well as creating group chats.

All works now. 👍🏻

**Pull request merged**
