### PR TITLE
tweak(phone/snackbar-provider): Altered API

### PR DESCRIPTION
**Pull request by TasoOneAsia**
Change to Snackbar message property to allow for any string rather than a translation key

**New**
```jsx
export const Snackbar = () => {
  const classes = useStyles();
  const { alert } = useSnackbar();

  return (
    <div className={classes.root}>
      {alert ? <Alert severity={alert.type}>{alert.message}</Alert> : null}
    </div>
  );
};
```

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
Could probably be cleaned up a little bit with a hook abstraction, but wanted to get this done so I could use the Snackbar provider in #134

**Review by erik-sn — APPROVED** [review]
I think this makes much more sense than trying to do the translation in the generic component.

**Review by jfrader — APPROVED** [review]

**Comment by jfrader** [comment]
@TasoOneAsia I would probably use useCallback for everything that goes into useNuiEvent, i changed messages one but the other `handleAddAlert` were not changed.

**Comment by TasoOneAsia** [comment]
@jfrader 🍪 as promised

**Comment by jfrader** [comment]
> @jfrader 🍪 as promised

I want a real cookie now :(

**Pull request merged**
